### ISSUE TITLE
[Bug]: It's not possible to basecall without a reference.

### ISSUE THREAD

**Issue by mattloose** [epi2me-labs/wf-basecalling#1]
### What happened?

I'd really like to be able to run dorado and generate an unaligned bam file of meth calls. For some reason a reference is compulsory for this workflow?

### Operating System

ubuntu 20.04

### Workflow Execution

EPI2ME Labs desktop application

### Workflow Execution - CLI Execution Profile

Singularity

### Workflow Version

revision: 2d733e8d7d [master]

### Relevant log output

```shell
ERROR: Validation of pipeline parameters failed!
* Missing required parameter: --ref
```

**Comment by SamStudio8** [comment]
Thank you for your valuable feedback @mattloose

**Comment by mattloose** [comment]
You are most welcome @SamStudio8 

In the end I just used dorado natively - but we like epi2melabs and are tyring to roll these pipelines out to other users around the university.

**Comment by SamStudio8** [comment]
@mattloose v0.4.0 has been updated to remove the requirement for a reference, please give it a try!

**Comment by mattloose** [comment]
Awesome - thank you.
