### ISSUE TITLE
[Bug]: Add support for duplex stereo basecalling

### ISSUE THREAD

**Issue by mdemouth** [epi2me-labs/wf-basecalling#10]
### What happened?

Would that be possible to add support for duplex stereo basecalling, wf-basecalling does not support it right now.

This is an ask from NVIDIA (@EpiSlim)

### Operating System

ubuntu 20.04

### Workflow Execution

Command line

### Workflow Execution - CLI Execution Profile

None

### Workflow Version

v0.7.1

### Relevant log output

```shell
No support for duplex stereo basecalling
```

**Comment by SamStudio8** [comment]
Hi @mdemouth, hang tight -- we're working on it! As we chunk pod5 inputs we need to do some restructuring to effectively recover duplex pairs from chunked inputs.

**Comment by mdemouth** [comment]
Thanks @SamStudio8 for the update. 
Do you have an ETA?

**Comment by SamStudio8** [comment]
@mdemouth No solid ETA but we have an internal candidate that we are testing now... Thanks for your patience!

**Comment by SamStudio8** [comment]
POD5 duplex basecalling has now been released in wf-basecalling 1.0.0.
