### ISSUE TITLE
dorado release timeline

### ISSUE THREAD

**Issue by istvankleijn** [epi2me-labs/wf-basecalling#13]
### Ask away!

How often/soon can we expect this workflow to update following new dorado releases? At the moment, I am looking forward to dorado@v0.3.2 and https://github.com/nanoporetech/dorado/issues/190 in particular, but would love to know if you have a more general strategy.
Thanks for providing these workflows, much appreciated!

**Comment by SamStudio8** [comment]
Hi @istvankleijn, thanks for your question. We generally aim to update the workflow within a week or two of updates to Dorado to give us time to test changes in wf-basecalling and other workflows that use the basecaller, but don't currently make any guarantees. I do have a ticket open for Dorado 0.3.2!
