### ISSUE TITLE
Syntax for calling multiple mods at once

### ISSUE THREAD

**Issue by annabel-NZ** [epi2me-labs/wf-basecalling#21]
### Ask away!

Hi @SamStudio8,
Please could you clarify the syntax for calling mod bases with more than one remora model at the same time (e.g. all context 5mC and 6mA)? 
I've attempted supplying two models separated by a comma (this errors out) and space separated (this completes but only reports the first model in the log).
Many thanks,
Annabel

**Comment by SamStudio8** [comment]
Hi @annabel-NZ, this is not currently supported by the workflow due to the way that model files are enumerated in our schemas to help users pick a model. This is something that we are looking at but I don't have an estimate of when it will be made available yet.

**Comment by sonalhenson** [comment]
Hi @SamStudio8, is this now possible with the current version of wf-basecalling? I'd like to call 4mC, 5mC and 6mA. 
Thanks
