### ISSUE TITLE
docker container for the v0.4.3 release

### ISSUE THREAD

**Issue by yuukiiwa** [epi2me-labs/wf-basecalling#24]
### Is your feature related to a problem?

We would want to use the `dorado v0.4.3` docker container for calling m6A

### Describe the solution you'd like

Can the docker container for `dorado v0.4.3` be made available, please?

### Describe alternatives you've considered

We are waiting for `dorado v0.4.3`

### Additional context

Thanks so much!!

**Comment by SamStudio8** [comment]
Hi @yuukiiwa, the dorado container is released as part of the wf-basecalling workflow. We have not yet updated to the latest Dorado but are doing our best to keep up. We'll likely look at this in the new year as more improvements to Dorado keep on coming!

**Comment by yuukiiwa** [comment]
Thanks so much, @SamStudio8!
