### ISSUE TITLE
wf_dorado:dorado(1) error, command exit status 125

### ISSUE THREAD

**Issue by c3305637** [epi2me-labs/wf-basecalling#25]
Hi, I'm trying to basecall from pod5 files and keep running into the error below.  I'm running Epi2me on a Linux machine.  Would the pod5 folder being located on a mapped network drive be contributing to this at all?  Log below.

This is epi2me-labs/wf-basecalling v1.1.1.
--------------------------------------------------------------------------------
[24/c4a324] Submitted process > cram_cache
[2c/d90b4b] Submitted process > getParams
[16/819179] Submitted process > wf_dorado:make_mmi
[0d/d88198] Submitted process > getVersions
[54/8a55bb] Submitted process > wf_dorado:dorado (1)
ERROR ~ Error executing process > 'wf_dorado:dorado (1)'
Caused by:
  Process `wf_dorado:dorado (1)` terminated with an error exit status (125)
Command executed:
  set +e
  source /opt/nvidia/entrypoint.d/*-gpu-driver-check.sh # runtime driver check msg
  set -e
  # CW-2569: convert the pod5s contextually
  if [[ "false" == "true" && "pod5" == "fast5" ]]; then
      pod5 convert fast5 ./*.fast5 --output . --threads 8 --one-to-one ./
  fi
  
  # Run dorado on the new pod5s
  dorado basecaller         ${DRD_MODELS_PATH}/dna_r10.4.1_e8.2_400bps_hac@v4.2.0         .         --modified-bases-models ${DRD_MODELS_PATH}/dna_r10.4.1_e8.2_400bps_hac@v4.2.0_5mCG_5hmCG@v2                  --device cuda:all | samtools view --no-PG -b -o 0.ubam -
  
  # CW-2569: delete the pod5s, if emit not required.
  if [[ "false" == "true" && "pod5" == "fast5" ]]; then
      rm -r converted/
  fi
Command exit status:
  125
Command output:
  (empty)
Command error:
  docker: invalid spec: /run/user/1000/gvfs/smb-share:server=resprsvm03.newcastle.edu.au,share=canepi/Sequencing_Data_Raw/1_RAW/230918_BH_Nanopore_AS/20230918_LEE12621A2_AS_SUPbasecalling/LEE12621A2_AS/20230918_1243_X3_FAV02769_33366469/pod5_pass:/run/user/1000/gvfs/smb-share:server=resprsvm03.newcastle.edu.au,share=canepi/Sequencing_Data_Raw/1_RAW/230918_BH_Nanopore_AS/20230918_LEE12621A2_AS_SUPbasecalling/LEE12621A2_AS/20230918_1243_X3_FAV02769_33366469/pod5_pass: too many colons.
  See 'docker run --help'.
Work dir:
  /media/ptwo/DataDisk/epi2melabs/instances/wf-basecalling_01HGVSVABBK5Y7QXYZDCR6M4WN/work/54/8a55bb9b58bd5389327245018d39c0
Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`
 -- Check '/media/ptwo/DataDisk/epi2melabs/instances/wf-basecalling_01HGVSVABBK5Y7QXYZDCR6M4WN/nextflow.log' file for details

**Comment by SamStudio8** [comment]
Hi @c3305637, I'm afraid I can't advise about mapping our containers to a Samba share specifically as this is beyond the scope of our support. I would advise that if possible, you instead mount the SMB share on the host that you run the workflow on and then refer to the paths as local paths to run the workflow from your box.
