### ISSUE TITLE
How to barcoding after basecalling?

### ISSUE THREAD

**Issue by msubirana** [epi2me-labs/wf-basecalling#29]
### Ask away!

Hi, 

I've just generated the SAMPLE.fastq.gz using wf-basecalling. How can I barcode this fastq to generated the fastq for each sample (barcode) generating the barcode01.fastq.gz, barcode02.fastq.gz...?

Thanks in advance.

**Comment by RenzoTale88** [comment]
Hi @msubirana check out the dorado documentation on barcoding [here](https://github.com/nanoporetech/dorado?tab=readme-ov-file#barcode-classification).
