### ISSUE TITLE
Adapter trimming

### ISSUE THREAD

**Issue by pawanchk** [epi2me-labs/wf-basecalling#30]
### Ask away!

Hi,

I have converted the fast5 files to pod5 for Nanopore DNA data using `pod5 convert fast5` tool and then I have used the `wf-basecalling` workflow to do base calling, the workflow has used `Dorado` version `0.3.4+5f5cd02` for base calling and `Minimap2` version `2.26-r1175` for obtaining an aligned bam file as I provided the reference sequence while running the  `wf-basecalling` workflow.

I have these queries -
1. whether adapter trimming is done as part of the `wf-basecalling` workflow by default or do I have to do additional steps for adapter trimming ?
2.  can the aligned bam file obtained in this step be used for variant calling using `wf-human-variation` workflow ?

**Comment by RenzoTale88** [comment]
Hi @pawanchk 
1. `dorado` should perform the DNA adapter trimming, as documented here for [v0.3.4](https://github.com/nanoporetech/dorado/tree/v0.3.4#dna-adapter-and-primer-trimming)
2. Yes they can. Simply provide the path to the BAM file with `--bam`.

Please note that `wf-human-variation` accept a single BAM file per sample, and therefore if you have multiple BAM for a single individual you want to combine them with `samtools merge`

**Comment by pawanchk** [comment]
Hi @RenzoTale88 

Thank you for your prompt response and clarification.

If I see the releases (https://github.com/nanoporetech/dorado/releases), `Primer and adapter trimming` (https://github.com/nanoporetech/dorado/commit/30e639cf66c1c24d0f61f1e7b91c6ce5db2cf7bf) are supported from version `v0.5.0` only. 

I think the link that you are pointing to in your response goes to the home page of `Dorado` caller and the `Readme` is same irrespective of which `tag` release is chosen. Please let me know if you think otherwise.

Is there any way to confirm that `v0.3.4` also did DNA adapter trimming ?

**Comment by RenzoTale88** [comment]
@pawanchk many apologies, that was my mistake. You're right, dorado v0.3.4 doesn't perform the trimming. You can trim your read post-basecalling by using the latest version of dorado with the `dorado trim` command, as described [here](https://github.com/nanoporetech/dorado#trimming-existing-datasets). Apologies again for the mistake.

**Comment by pawanchk** [comment]
@RenzoTale88 Thank you so much for your clarification. I tried trimming using the post-basecalling `bam` file using `dorado trim` but it ends in `Segmentation fault      (core dumped)`. 

I tried Dorado version `0.5.2+7969fab`. Can I please know how I can resolve this ?

**Comment by RenzoTale88** [comment]
@pawanchk this is an issue that you need to raise with the dorado team using the appropriate GitHub issue page [here](https://github.com/nanoporetech/dorado/issues)
