### ISSUE TITLE
Barcode demultiplexing

### ISSUE THREAD

**Issue by danpal96** [epi2me-labs/wf-basecalling#36]
### Is your feature related to a problem?

I want to be able to demultiplex my samples using EPI2ME

### Describe the solution you'd like

An implementation of barcode demultiplexing in this workflow or on a new one

### Describe alternatives you've considered

I can use dorado demux in the terminal but I want to teach some people that don't know how to use the terminal

**Comment by SamStudio8** [comment]
Thanks for taking the time to make a feature request @danpal96. Supporting the newest features of Dorado is on our list to better support users of the desktop application but we cannot give an estimate of when they will be implemented at this time.
