### ISSUE TITLE
How to set the --trim parameter in Dorado when running wf-basecalling

### ISSUE THREAD

**Issue by CyberGypsy6324** [epi2me-labs/wf-basecalling#40]
Hi,

I wondered if I could change the parameter `--trim` in Dorardo when running `wf-basecalling`. Based on the description in Dorado's documentation (https://github.com/nanoporetech/dorado?tab=readme-ov-file#dna-adapter-and-primer-trimming), both adapters and primers will be trimmed. I want to keep the primers in the output FASTQ files, which is to use `--trim adapters`.

Thank you.

**Comment by RenzoTale88** [comment]
@CyberGypsy6324 you can provide additional basecaller arguments using the `--basecaller_args` option.

**Comment by CyberGypsy6324** [comment]
Ok, I see. Thank you.
