### ISSUE TITLE
What arguments are accepted for demux_args?

### ISSUE THREAD

**Issue by chrismitbiz** [epi2me-labs/wf-basecalling#41]
### Ask away!

Under the advanced basecalling options, what arguments are accepted for demux_args? It is described as `Additional command line arguments to pass to the basecaller barcoding process.` but no options are provided. 

Thank you!

**Comment by cjw85** [comment]
The value of this argument is [passed verbatim](https://github.com/epi2me-labs/wf-basecalling/blob/d42fa90419f78b0f597c2267088343ad05509b50/lib/signal/ingress.nf#L77
) to dorado when performing demultiplexing, they can be anything that would be valid for running dorado stand-alone.

See: [dorado documentation](https://github.com/nanoporetech/dorado?tab=readme-ov-file#barcode-classification)

**Comment by chris-krohn** [comment]
can you provide an example for multiple arguments. the expected syntax is unclear to the the uninitiated. thank you
