### ISSUE TITLE
2 Run failed on same step - wf_dorado:align_and_qsFilter

### ISSUE THREAD

**Issue by fidibidi** [epi2me-labs/wf-basecalling#47]
### Operating System

Ubuntu 22.04

### Workflow Version

v1.3.0

### Workflow Execution

Other (please describe)

### Other workflow execution

AWS EC2 Instance; via CLI

### CLI command run

nextflow run epi2me-labs/wf-basecalling -profile standard --input /home/ubuntu/data/A0035/pod5s/ --sample_name A0035 --ref references/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna --dorado_ext pod5 --out_dir /home/ubuntu/data/wf-basecall-A0035 --basecaller_cfg dna_r10.4.1_e8.2_400bps_hac@v5.0.0 --remora_cfg dna_r10.4.1_e8.2_400bps_hac@v5.0.0_5mCG_5hmCG@v1 --threads 16 --output_bam True --bam_min_coverage 0 -resume

### Workflow Execution - CLI Execution Profile

standard (default)

### What happened?

Run crashed on the align_and_qsFilter step for two seperate samples. I've successfully run this pipeline in the cloud before, but this was the first time I added the line output_bam True, and in both the alignment step failed. 

Resuming fails as well. Even if resuming with the output_bam line removed from the command. 

Which leads me to my question... Is it possible to clear all cached data for this step, and resume that step freshly? And with the output_bam option removed? At this point I've spent a decent amount of money running the script in the cloud... and for it to crash here and me not able to get the crams or bams, would be a big loss... so any ideas on salvaging would be appreciated. 

### Relevant log output

```shell
Workflow execution completed unsuccessfully!
The exit status of the task that caused the workflow execution to fail was: 1.

The full error message was:

Error executing process > 'wf_dorado:align_and_qsFilter (3)'

Caused by:
  Process `wf_dorado:align_and_qsFilter (3)` terminated with an error exit status (1)


Command executed:

  samtools bam2fq -@ 1 -T 1 2.ubam         | minimap2 -y -t 8 -ax map-ont ref.mmi -         | samtools sort -@ 3         | samtools view -e '[qs] >= 10'               --output 2.pass.cram               --unoutput 2.fail.cram               -O CRAM --reference GCA_000001405.15_GRCh38_no_alt_analysis_set.fna -

Command exit status:
  1

Command output:
  (empty)

Command error:
  [M::main::10.383*0.79] loaded/built the index for 195 target sequence(s)
  [M::mm_mapopt_update::12.333*0.83] mid_occ = 694
  [M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 195
  [M::mm_idx_stat::13.374*0.84] distinct minimizers: 100167746 (38.80% are singletons); average occurrences: 5.519; average spacing: 5.607; total length: 3099922541
  [M::worker_pipeline::201.563*7.26] mapped 79578 sequences
  [M::worker_pipeline::379.871*7.61] mapped 88177 sequences
  [M::worker_pipeline::573.849*7.75] mapped 86498 sequences
  [M::worker_pipeline::733.696*7.81] mapped 86207 sequences
  samtools sort: failed writing to "./samtools.35.6008.tmp.0001.bam": Inappropriate ioctl for device
  [main_samview] fail to read the header from "-".

Work dir:
  /home/ubuntu/work/a6/88de26c908eea3fd6e5a75e12f1698

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`
```

### Were you able to successfully run the latest version of the workflow with the demo data?

yes

**Comment by fidibidi** [comment]
I believe the issue was with my local storage running out...

**Comment by SamStudio8** [comment]
Aha! Glad things are working for you now.
