### ISSUE TITLE
Custom barcodes

### ISSUE THREAD

**Issue by Goraichuk** [epi2me-labs/wf-basecalling#57]
### Ask away!

Hi! Does wf-basecalling support demultiplexing with custom barcodes? If so, how to provide custom barcode kit arrangements and sequences?

**Comment by mattdmem** [comment]
Hello @Goraichuk  - not at the moment, but I've flagged it up as a feature request.

Thanks

Matt

**Comment by lonsbio** [comment]
:+1: this would be great
