### ISSUE TITLE
Error in base.config when specifying containers for profile=awsbatch

### ISSUE THREAD

**Issue by joshamilton** [epi2me-labs/wf-basecalling#59]
### Operating System

Ubuntu 22.04

### Workflow Version

v1.4.3

### Workflow Execution

Command line (Cluster)

### Workflow Execution - CLI Execution Profile

custom

### What happened?

I am trying to run the pipeline on AWS Batch usintg the 'awsbatch' config and the demo data. As part of my nextflow configuration, I specify `aws_image_prefix = ontresearch`, so I can pull the public ONT Docker containers. The pipeline fails because there is a syntax error in base.config, lines 71, 82, 85. These lines contain a '-' between the image prefix and image name, when there should be a '/'. For example:

`container = "${params.aws_image_prefix}-wf-common:${params.wf.common_sha}"`

should be

`container = "${params.aws_image_prefix}/wf-common:${params.wf.common_sha}"`

Otherwise, Docker will fail to pull the container.

### Relevant log output

```shell
ERROR ~ Error executing process > 'prepare_reference:cram_cache (1)'
Caused by:
  Task failed to start - CannotPullImageManifestError: Error response from daemon: errors:
  denied: requested access to the resource is denied
  unauthorized: authentication required
Command executed:
  # Invoke from binary installed to container PATH
  seq_cache_populate.pl -root ref_cache/ GCA_000001405.15_GRCh38_no_alt_analysis_set.fasta
  REF_PATH="ref_cache/%2s/%2s/%s"
Command exit status:
  -
Command output:
  (empty)
Work dir:
  s3://seqcoast-scratch/scratch/4sdtD0A6RwX5nb/6f/2b954d107ae121cf7942d03c17e415
Container:
  ontresearch-wf-common:shabadd33adae761be6f2d59c6ecfb44b19cf472cfc
Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`
-- Check 'nf-4sdtD0A6RwX5nb.log' file for details
[13/e64e8b] Re-submitted process > getVersions
WARN: Killing running tasks (6)
```

### Were you able to successfully run the latest version of the workflow with the demo data?

no

**Comment by SamStudio8** [comment]
Hi @joshamilton, this is intentional and not a syntax error for our use-case. If you need to change these parameters you can do so by specifying your own Nextflow profile.
