### ISSUE TITLE
[Bug]: Not compatible with Azure batch executor

### ISSUE THREAD

**Issue by benbfly** [epi2me-labs/wf-basecalling#6]
### What happened?

I will add more details later, but has to do with the implementation of the Nvidia container toolkit on Azure batch. The "--gpus all" container option can not be passed as a container option, or you get the "ContainerInvalidSettings" error below.

If the "--gpus all" is removed, the nanoporetech/dorado container can not recognize the GPU.  You get an error `[error] CUDA device requested but no devices found.`

Other containers I tried that are based on nvidia/cuda do not have the same problem.  I am trying to track down the incompatibility - **it would be helpful if I had access to the Dockerfile for nanoporetech/dorado. Could you provide that to me?**

Thanks!

### Operating System

ubuntu 20.04

### Workflow Execution

Command line

### Workflow Execution - CLI Execution Profile

Docker

### Workflow Version

live from epi2me-labs/wf-basecalling

### Relevant log output

```shell
"failureInfo": {
      "category": "UserError",
      "code": "ContainerInvalidSettings",
      "message": "At least one value of specified task container settings is invalid",
      "details": [
        {
          "name": "ContainerSettings",
          "value": "--gpus all"
        },
        {
          "name": "Message",
          "value": "Some supplied docker options are not recognized or are unsupported: --gpus, all"
        }
      ]
    },
```

**Comment by benbfly** [comment]
I believe you are relying on the "--gpus" to add all the nvidia libraries and environment variables, whereas Azure batch expects thos to be present inside the container. 

For instance, the nvidia/cuda container (which works fine with Azure batch) installs the libcudart runtime library by default, whereas nanoporetech/dorado has no libcuda built in.  If you use --gpus, it does add "libcuda", which is probably why this works with AWS. But Azure batch for some reason does not allow "--gpus".

```
upwmvs@885f9db0e8cf401798bf4634aea31342000000:~$ sudo docker run -it --entrypoint /bin/bash nanoporetech/dorado:shac9cd8d6dd1076bf0290ef36c7531c83bd1003302
epi2melabs@fbae63f2a168:~$ ldconfig -p | grep libcuda
epi2melabs@fbae63f2a168:~$ 

upwmvs@885f9db0e8cf401798bf4634aea31342000000:~$ sudo docker run --gpus all -it --entrypoint /bin/bash nanoporetech/dorado:shac9cd8d6dd1076bf0290ef36c7531c83bd1003302
epi2melabs@a32c4bc2b206:~$ ldconfig -p | grep libcuda
        libcuda.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libcuda.so.1
epi2melabs@a32c4bc2b206:~$ 

upwmvs@885f9db0e8cf401798bf4634aea31342000000:~$ sudo docker run -it --entrypoint /bin/bash nvidia/cuda:12.1.1-runtime-ubuntu22.04
root@c50739b8b518:/# ldconfig -p | grep libcuda
        libcudart.so.12 (libc6,x86-64) => /usr/local/cuda/targets/x86_64-linux/lib/libcudart.so.12
root@c50739b8b518:/# 

upwmvs@885f9db0e8cf401798bf4634aea31342000000:~$ sudo docker run --gpus all -it --entrypoint /bin/bash nvidia/cuda:12.1.1-runtime-ubuntu22.04
root@6b2712a9d9c2:/# ldconfig -p | grep libcuda
        libcudart.so.12 (libc6,x86-64) => /usr/local/cuda/targets/x86_64-linux/lib/libcudart.so.12
        libcuda.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libcuda.so.1
root@c50739b8b518:/#


```

**Comment by benbfly** [comment]
The relevant Azure documentation on "Container Workloads" contains the following note:

- "For container pools with GPU-enabled hardware, Batch automatically enables GPU for container tasks, so you shouldn't include the –gpus argument."

(source https://learn.microsoft.com/en-us/azure/batch/batch-docker-container-workloads#container-settings-for-the-task)

**Comment by SamStudio8** [comment]
Hi @benbfly, thanks for taking the time to report this. The Dorado container has been updated as part of the release of wf-basecalling 0.5.0. Can you pull the latest version of the workflow (`nextflow pull epi2me-labs/wf-basecalling`) to see if this issue has been resolved? In case you want to experiment with the container directly, the new image tag is: `sha1b00def6c21f62c42ffc6726c4da9d8960c3b7ef`.

**Comment by SamStudio8** [comment]
> As long as you leave the "--gpus all" as a container option in nextflow.config, Azure batch will reject it.

Indeed, we don't currently support pipelines on Azure directly, so our workflows do not ship with a profile for it (but this discussion is proving useful!). Options in our `nextflow.config` can always be overridden by users via Nextflow's flexible configuration system. `--gpus all` is included by default as it is required in the general case.

>  I am using 9.4.1 configs, are those not in the container any more (I believe they were in the last version

I have looked into this and see that the previous version of the Dorado container incorrectly referred to that model with the version number `3.4`, whereas it should have been `3.3` to match the simplex basecalling model. The model was updated in the container, but our workflow schema that lists the valid options was not updated. This has now been fixed in version 0.5.1 that we have just released. You'll need the `dna_r9.4.1_e8_sup@v3.3_5mCG@v0` modbase model now. Please give this a try (--gpus all notwithstanding) and see if it works for you!

**Comment by benbfly** [comment]
Now it works!  The only remaining thing would be to make an Azure profile to remove `--gpus all`. In the meantime, I would recommend putting a prominent note in the documentation because the resulting Azure batch error message is useless (it doesn't mention `--gpus`).
<img width="1119" alt="image" src="https://github.com/epi2me-labs/wf-basecalling/assets/1547787/edfd94d8-d33a-4a87-8772-8ba2857dfa14">

**Comment by benbfly** [comment]
I'm happy (eager, actually) to beta test the version 0.3.0 container when it's ready. Thanks!
