### ISSUE TITLE
[Bug]: Having problems with: ERROR ~ Error executing process > 'wf_dorado:dorado (1)'

### ISSUE THREAD

**Issue by MarioCazalla** [epi2me-labs/wf-basecalling#9]
### What happened?

Hi all,
I am executing EPI2ME in windows 11 and I have problems when wf:dorado is runing

Can anyone help me?
Thanks in advance

### Operating System

Windows 11

### Workflow Execution

EPI2ME Labs desktop application

### Workflow Execution - CLI Execution Profile

Docker

### Workflow Version

v0.7.1

### Relevant log output

```shell
_Command executed:
  set +e
  source /opt/nvidia/entrypoint.d/*-gpu-driver-check.sh # runtime driver check msg
  set -e
  dorado basecaller         ${DRD_MODELS_PATH}/dna_r9.4.1_e8_fast@v3.4 .                           --device cuda:all | samtools view --no-PG -b -o 0.ubam -
Command exit status:
  125
Command output:
  (empty)
Command error:
  docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy'
  nvidia-container-cli: initialization error: WSL environment detected but no adapters were found: unknown._
```

**Comment by SamStudio8** [comment]
Hi @MarioCazalla. Currently, Windows should not be considered as a supported operating system for wf-basecalling as it cannot reliably perform basecalling through Docker. Users are encouraged to download Dorado for Windows directly from the Dorado GitHub repository here: https://github.com/nanoporetech/dorado#installation.

We do not directly support configuration of accelerated computing through WSL2 and Docker on Windows, but it is possible to set up for most versions of Windows 11 and some versions of Windows 10 and we direct users to the CUDA on WSL User Guide here: https://docs.nvidia.com/cuda/wsl-user-guide/index.html.
